# Generated by Django 5.2.8 on 2025-11-19 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Name', models.CharField(max_length=100)),
                ('Product_Id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Brand_Name', models.CharField(max_length=30)),
                ('Date_Of_Manufacture', models.DateField()),
                ('Expire_Date', models.DateField()),
                ('Price', models.FloatField()),
                ('Stockavailable', models.IntegerField()),
            ],
        ),
    ]
